{
 "title": "sinus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "content": "\n# CPU consumption\n\nThis metric provides the CPU consumption for each running flow. It is an overall consumption of the different replicas.\n\n\n\n"
  },
  {
   "title": "CPU ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Tester CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"cpu_usage_nanocores\")/1000000000 FROM \"kubernetes_pod_container\" WHERE (\"pod_name\" =~ /^nodered-.*-tester.*$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sinus CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"cpu_usage_nanocores\")/1000000000 FROM \"kubernetes_pod_container\" WHERE (\"pod_name\" =~ /^nodered-.*-sinus.*$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "content": "\n# Number of replicas\n\nThis metrics provides the number of replicas for each running flow.\n\n\n\n"
  },
  {
   "title": "Nb replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Timer replicas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"gauge\") FROM \"kubernetes_deployment_status_replicas_available\" WHERE  (\"deployment\" =~ /^nodered-.*-tester/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sinus replicas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"gauge\") FROM \"kubernetes_deployment_status_replicas_available\" WHERE  (\"deployment\" =~ /^nodered-.*-sinus/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Counters",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "content": "\n# Flows counters\n\nThis metrics provide the values of the different counters introduced in the flows.\n\n\n\n"
  },
  {
   "title": "Flows counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sinus REQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(\"max\",1s) from (SELECT max(\"sum\") as \"max\"  from (SELECT sum(\"counter\") as \"sum\" FROM \"af_node_red_counter_metric_sinusrequests\" WHERE (\"flowId\" = 'tester' ) AND $timeFilter GROUP BY time($__interval) fill(previous)) WHERE $timeFilter GROUP BY time(1m) fill(previous)) where $timeFilter fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sinus Result received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(\"max\",1s) from (SELECT max(\"sum\") as \"max\"  from (SELECT sum(\"counter\") as \"sum\" FROM \"af_node_red_counter_metric_sinusresults\" WHERE (\"flowId\" = 'tester' ) AND $timeFilter GROUP BY time($__interval) fill(previous)) WHERE $timeFilter GROUP BY time(1m) fill(previous)) where $timeFilter fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sinus Calculated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(\"max\",1s) from (SELECT max(\"sum\") as \"max\"  from (SELECT sum(\"counter\") as \"sum\" FROM \"af_node_red_counter_metric_sinuscomputed\" WHERE (\"flowId\" = 'sinus' ) AND $timeFilter GROUP BY time($__interval) fill(previous)) WHERE $timeFilter GROUP BY time(1m) fill(previous)) where $timeFilter fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lives Counters",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "content": "\n# Counters\n\nThis metrics provide the current values of the diffrent counters defined in the flows.\n\n\n\n"
  },
  {
   "title": "Lives counters",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 24 },
   "targets": [
    {
     "alias": "Sinus Requests",
     "measurement": "af_node_red_counter_metric_sinusrequests",
     "query": "SELECT sum(\"counter\") FROM \"af_node_red_counter_metric_sinusrequests\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Sinus Results",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "af_node_red_counter_metric_sinusresults",
     "query": "SELECT sum(\"counter\") FROM \"af_node_red_counter_metric_sinusresults\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Sinus Computed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "af_node_red_counter_metric_sinuscomputed",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}